services:
  mysql:
    image: mysql:8.0
    container_name: sis-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: "Asia/Ho_Chi_Minh"
    ports:
      - "${DB_PORT}:3306"
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - mysql_data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    networks:
      - scc-sis-network

  phpmyadmin:
    image: phpmyadmin:5
    container_name: sis-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      TZ: "Asia/Ho_Chi_Minh"
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      - mysql
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - scc-sis-network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: sis-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      TZ: "Asia/Ho_Chi_Minh"
    networks:
      - scc-sis-network
    restart: unless-stopped

  backend:
    image: huy210205/scc-sis-be:huy2.3
    container_name: scc-sis-be
    depends_on:
      - mysql
      - qdrant
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SERVER_PORT: 7000
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      TZ: "Asia/Ho_Chi_Minh"
    ports:
      - "7000:7000"
    networks:
      - scc-sis-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7000/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: huy210205/scc-sis-fe:huy2.5
    container_name: scc-sis-fe
    depends_on:
      - backend
    environment:
      TZ: "Asia/Ho_Chi_Minh"
    ports:
      - "5173:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - scc-sis-network
    restart: unless-stopped

volumes:
  mysql_data:
    name: ${VOLUME_NAME}
    external: true
  qdrant_data:

networks:
  scc-sis-network:
    driver: bridge
